### PR TITLE
add note the celery config file where we are not in production

### PR DESCRIPTION
**Pull request by Gustry**

### CODE REVIEW

**Comment by lucernae** [comment]
LGTM!
I suggests @ismailsunni to fix this too in the docker-entrypoint.

**Comment by Gustry** [comment]
I'm confused. I understood yesterday that it was a bug and not a feature. So I understood that @ismailsunni is going to fix it and I will have to close this PR. Is it not right?

**Comment by lucernae** [comment]
No, that's ok. What @ismailsunni will fix is just to have it copied automatically on first setup.
But your Readme is still relevant. Developer can copy it themselves if he wants to have more specific settings (not from environment).

**Comment by Gustry** [comment]
OK !

**Pull request merged**
